# Generated by Django 2.2 on 2019-08-21 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('idno', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('Hb', models.CharField(max_length=30)),
                ('GlbLevel', models.CharField(max_length=30)),
                ('HlBac', models.CharField(max_length=30)),
                ('Heatbeet', models.CharField(max_length=30)),
                ('Oxeygenlevel', models.CharField(max_length=30)),
                ('Bmi', models.CharField(max_length=30)),
            ],
        ),
    ]
